export const PROFILE_DATA = {
  user: {
    name: "Батболд Д.",
    grade: "ШУТИС — Мэдээлэл, компьютерийн ухаан",
    completedAt: "2026-08-24",
    totalXP: 370,
  },
  mbti: {
    type: "INTJ",
    mongolianName: "Стратег",
    tagline: "Системчилсэн, урт хугацааны стратегийн сэтгэгч",
    description:
      "Та бие даасан, шинжлэх ухааны сэтгэлгээтэй, цаашдын зорилгоо тодорхой харж чаддаг хүн. Нарийн төвөгтэй асуудлуудыг задлан шинжилж, системт шийдэл олоход ер бусын авьяастай.",
    dimensions: [
      {
        id: "dim-ie",
        left: "Introvert (I)",
        right: "Extravert (E)",
        value: 78,
        side: "left" as const,
        label: "I",
      },
      {
        id: "dim-sn",
        left: "Sensing (S)",
        right: "Intuition (N)",
        value: 68,
        side: "right" as const,
        label: "N",
      },
      {
        id: "dim-tf",
        left: "Thinking (T)",
        right: "Feeling (F)",
        value: 82,
        side: "left" as const,
        label: "T",
      },
      {
        id: "dim-jp",
        left: "Judging (J)",
        right: "Perceiving (P)",
        value: 71,
        side: "left" as const,
        label: "J",
      },
    ],
    compatibleTypes: ["ENTJ", "INFJ", "ENTP", "INTP"],
    workStyle: "Ганцаараа гүнзгий ажиллах, бүтэцтэй орчин, тодорхой зорилготой",
  },
  iq: {
    totalScore: 124,
    label: "Өндөр",
    percentile: 92,
    description:
      "Хурдан суралцагч, нарийн ажлыг хийж чадна. Олон мэргэжилд амжилттай ажиллах чадвартай.",
    subScores: [
      {
        id: "iq-sub-logic",
        category: "Логик",
        score: 88,
        max: 100,
        color: "#2563EB",
      },
      {
        id: "iq-sub-visual",
        category: "Орон зай",
        score: 74,
        max: 100,
        color: "#7C3AED",
      },
      {
        id: "iq-sub-language",
        category: "Хэл / Дүн шинжилгээ",
        score: 79,
        max: 100,
        color: "#059669",
      },
      {
        id: "iq-sub-divergent",
        category: "Бүтээлч / Дивергент",
        score: 65,
        max: 100,
        color: "#D97706",
      },
    ],
  },
  skills: {
    radarData: [
      { subject: "Техник", value: 82, fullMark: 100 },
      { subject: "Нийгмийн", value: 54, fullMark: 100 },
      { subject: "Бүтээлч", value: 61, fullMark: 100 },
      { subject: "Удирдлага", value: 73, fullMark: 100 },
    ],
    summary:
      "Техникийн болон удирдлагын чадвар хүчтэй. Нийгмийн харилцааны чадварыг хөгжүүлэх шаардлагатай.",
    strengths: [
      "Алгоритм сэтгэлгээ",
      "Системийн дизайн",
      "Стратегийн төлөвлөлт",
      "Асуудал шийдвэрлэлт",
    ],
    gaps: ["Олны өмнө ярих", "Багийн харилцаа", "Бүтээлч дизайн"],
  },
  professions: [
    {
      id: "prof-software",
      rank: 1,
      name: "Програм хангамжийн инженер",
      englishName: "Software Engineer",
      matchPct: 94,
      salaryMin: 2500000,
      salaryMax: 6000000,
      demand: "Маш өндөр",
      demandLevel: "very-high",
      trend: "↑↑",
      description:
        "Програм хангамж боловсруулах, систем дизайн хийх, багаар ажиллах. Таны INTJ + өндөр логик чадвар + техникийн ур чадвар энэ мэргэжилтэй маш сайн нийцэж байна.",
      skills: [
        "Python / JavaScript",
        "Системийн дизайн",
        "Алгоритм",
        "Git / CI/CD",
      ],
      environment: "Технологийн компани, стартап, remote ажиллагаа",
    },
    {
      id: "prof-data",
      rank: 2,
      name: "Дата шинжээч / AI инженер",
      englishName: "Data Analyst / AI Engineer",
      matchPct: 91,
      salaryMin: 2500000,
      salaryMax: 7000000,
      demand: "Маш өндөр",
      demandLevel: "very-high",
      trend: "↑↑↑",
      description:
        "Өгөгдлийн дүн шинжилгээ, машин сургалт, бизнесийн шийдвэр гаргалтыг дэмжих. Таны аналитик сэтгэлгээ болон логик чадвар энд онцгой давуу тал болно.",
      skills: ["Python / R", "SQL", "Machine Learning", "Tableau / Power BI"],
      environment:
        "Санхүүгийн байгууллага, технологийн компани, судалгааны төв",
    },
    {
      id: "prof-architect",
      rank: 3,
      name: "Системийн архитектор",
      englishName: "Systems Architect",
      matchPct: 87,
      salaryMin: 3500000,
      salaryMax: 8000000,
      demand: "Өндөр",
      demandLevel: "high",
      trend: "↑",
      description:
        "Томоохон мэдээллийн системийг дизайн хийх, техникийн стратеги боловсруулах. Таны INTJ стратегийн сэтгэлгээ болон системт хандлага энд хамгийн сайн илэрнэ.",
      skills: [
        "Cloud Architecture",
        "Microservices",
        "Security Design",
        "Leadership",
      ],
      environment: "Томоохон IT компани, банк, засгийн газрын байгууллага",
    },
    {
      id: "prof-pm",
      rank: 4,
      name: "Бүтээгдэхүүний менежер",
      englishName: "Product Manager",
      matchPct: 79,
      salaryMin: 2000000,
      salaryMax: 5000000,
      demand: "Өндөр",
      demandLevel: "high",
      trend: "↑",
      description:
        "Технологийн бүтээгдэхүүний стратеги, roadmap, баг удирдлага. Таны аналитик + удирдлагын чадвар хослол нь энэ үүрэгт тохирно. Нийгмийн харилцааны чадварыг хөгжүүлэх шаардлагатай.",
      skills: [
        "Product Strategy",
        "Agile / Scrum",
        "User Research",
        "Data Analysis",
      ],
      environment: "Технологийн компани, стартап, e-commerce",
    },
    {
      id: "prof-researcher",
      rank: 5,
      name: "Судлаач / Эрдэм шинжилгээч",
      englishName: "Research Scientist",
      matchPct: 74,
      salaryMin: 1800000,
      salaryMax: 4500000,
      demand: "Дунд",
      demandLevel: "medium",
      trend: "→",
      description:
        "Шинжлэх ухааны судалгаа, нийтлэл, нээлт. Таны INTJ хувь хүний онцлог судалгааны ажилд маш тохиромжтой боловч Монголын хөдөлмөрийн зах зээлд хязгаарлагдмал боломжтой.",
      skills: [
        "Судалгааны арга зүй",
        "Статистик",
        "Нийтлэл бичих",
        "Тэтгэлэг авах",
      ],
      environment: "Их сургууль, судалгааны хүрээлэн, олон улсын байгууллага",
    },
  ],
  universities: [
    {
      id: "uni-shutis",
      name: "ШУТИС",
      fullName: "Шинжлэх ухаан технологийн их сургууль",
      programs: [
        "Мэдээлэл, компьютерийн ухаан",
        "Програм хангамж",
        "Мэдээллийн систем",
      ],
      matchScore: 96,
      location: "Улаанбаатар",
      type: "Улсын",
      tuition: "2,800,000 – 3,500,000₮/жил",
      highlight: "IT мэргэжлийн хамгийн том сургуультай",
    },
    {
      id: "uni-muis",
      name: "МУИС",
      fullName: "Монгол Улсын Их Сургууль",
      programs: ["Мэдээллийн технологи", "Математик", "Физик"],
      matchScore: 88,
      location: "Улаанбаатар",
      type: "Улсын",
      tuition: "2,400,000 – 3,200,000₮/жил",
      highlight: "Монголын хамгийн нэр хүндтэй их сургууль",
    },
    {
      id: "uni-mjis",
      name: "МЖИС",
      fullName: "Монгол Японы Их Сургууль",
      programs: ["IT менежмент", "Програм хангамж", "Мэдээллийн систем"],
      matchScore: 82,
      location: "Улаанбаатар",
      type: "Хамтарсан",
      tuition: "3,500,000 – 4,800,000₮/жил",
      highlight: "Японы технологийн стандарт, олон улсын гэрчилгээ",
    },
    {
      id: "uni-num",
      name: "NUM",
      fullName: "National University of Mongolia",
      programs: ["Computer Science", "Engineering", "Mathematics"],
      matchScore: 77,
      location: "Улаанбаатар",
      type: "Улсын",
      tuition: "2,200,000 – 3,000,000₮/жил",
      highlight: "Англи хэлний сургалт, олон улсын харилцаа",
    },
  ],
  workEnvironments: [
    {
      id: "env-remote",
      icon: "💻",
      title: "Remote / Цахим ажиллагаа",
      match: 95,
      desc: "Гэрт буюу хаанаас ч ажиллах боломж",
    },
    {
      id: "env-startup",
      icon: "🚀",
      title: "Стартап",
      match: 88,
      desc: "Хурдан шийдвэр, олон үүрэг, хувьсал",
    },
    {
      id: "env-tech",
      icon: "🏢",
      title: "Технологийн компани",
      match: 85,
      desc: "Бүтэцтэй орчин, мэргэжлийн өсөлт",
    },
    {
      id: "env-research",
      icon: "🔬",
      title: "Судалгааны байгууллага",
      match: 79,
      desc: "Гүнзгий судалгаа, шинэ нээлт",
    },
  ],
  collaborationStyles: [
    {
      id: "collab-async",
      style: "Async харилцаа",
      desc: "Цахим бичиг, документ, тодорхой даалгавар",
      match: "Маш тохиромжтой",
    },
    {
      id: "collab-small",
      style: "Жижиг баг (2-5 хүн)",
      desc: "Мэргэжилтнүүдийн нягт хамтын ажиллагаа",
      match: "Тохиромжтой",
    },
    {
      id: "collab-independent",
      style: "Бие даасан ажил",
      desc: "Ганцаараа гүнзгий ажиллах, бие даасан шийдвэр",
      match: "Маш тохиромжтой",
    },
    {
      id: "collab-large",
      style: "Том баг / олон нийт",
      desc: "Олон хүнтэй байнгын харилцаа",
      match: "Бага тохиромжтой",
    },
  ],
  roadmap: [
    {
      id: "roadmap-phase1",
      phase: 1,
      title: "Одоогийн: Үнэлгээ & Карьер тохирол",
      status: "current" as const,
      color: "bg-primary",
      items: [
        "MBTI + IQ + Ур чадварын тест",
        "AI карьерийн профайл",
        "Их сургуулийн санал",
        "Хөдөлмөрийн зах зээлийн мэдээлэл",
      ],
      xp: 370,
    },
    {
      id: "roadmap-phase2",
      phase: 2,
      title: "Q2 2026: AI Даалгавар & Суралцах зам",
      status: "upcoming" as const,
      color: "bg-info",
      items: [
        "Claude API-р автомат даалгавар үүсгэх",
        "Monaco Editor + Python sandbox",
        "XP суурь алгоритм",
        "Мэргэжил тус бүрийн суралцах зам",
      ],
      xp: 500,
    },
    {
      id: "roadmap-phase3",
      phase: 3,
      title: "Q3 2026: AI Ментор & Кодын дүн шинжилгээ",
      status: "planned" as const,
      color: "bg-violet-500",
      items: [
        "Streaming chat интерфейс",
        "Алдааны хэв маягийг илрүүлэх",
        "Алхам алхмаар удирдамж",
        "Хувийн суралцах тэмдэглэл",
      ],
      xp: 800,
    },
    {
      id: "roadmap-phase4",
      phase: 4,
      title: "Q4 2026: Micro Simulation + XP Систем",
      status: "planned" as const,
      color: "bg-accent",
      items: [
        "Компанийн хамтын ажиллагааны симуляц",
        "Болор гэрчилгээ",
        "Streak систем",
        "Leaderboard & Badge",
      ],
      xp: 1200,
    },
  ],
};
